### ISSUE TITLE
Fluent API cause panic

### ISSUE THREAD

**Issue by edward-yakop** [DrSmithFr/go-console#10]
Steps to reproduce bug:
1. Type the following code:
  `_ = go_console.NewCli()`

Expected result:
1. Cli is created

Current result:
1. The following panic occurs:

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x533308]
>
> goroutine 1 [running]:
> github.com/DrSmithFr/go-console.(*Cli).AddInputOption(0xc000188200, 0xc0000a70e0)
>        /home/efy/.go/pkg/mod/github.com/!dr!smith!fr/go-console@v0.0.0-20230310233733-3f52e5ceff45/go-console.go:148 +0x48
> github.com/DrSmithFr/go-console.(*Cli).addDefaultOptions(0x126c178?)
>        /home/efy/.go/pkg/mod/github.com/!dr!smith!fr/go-console@v0.0.0-20230310233733-3f52e5ceff45/go-console.go:110 +0x85
> github.com/DrSmithFr/go-console.CustomCli({0xdcb6e8?, 0xc0000000c0}, {0xdc8e18, 0xc000099340})
>        /home/efy/.go/pkg/mod/github.com/!dr!smith!fr/go-console@v0.0.0-20230310233733-3f52e5ceff45/go-console.go:42 +0x4e
> github.com/DrSmithFr/go-console.NewCli()
>        /home/efy/.go/pkg/mod/github.com/!dr!smith!fr/go-console@v0.0.0-20230310233733-3f52e5ceff45/go-console.go:29 +0x51

**Comment by DrSmithFr** [comment]
Hi @edward-yakop,

Your using an old version of the package, the new way to create the equivalent to `_ = go_console.NewCli()` is :

```go
package main

import (
	"github.com/DrSmithFr/go-console"
)

func main() {
	_ = go_console.NewScript()
}
```
